-- IMS ERP roles and permissions for Supabase Postgres
-- Generated from prisma/seed.ts plus all UI/API permission references.
-- Safe to run more than once in the Supabase SQL Editor.

BEGIN;

-- 1. Roles
WITH role_seed(code, name, description, is_system_role) AS (
  VALUES
    ('SUPER_ADMIN', 'Super Admin', 'Full system access', true),
    ('COMPANY_ADMIN', 'Company Admin', 'All operational and company administration permissions', true),
    ('BRANCH_MANAGER', 'Branch Manager', 'Branch operations manager', true),
    ('DEPT_HEAD', 'Department Head', 'Department operations and approvals', true),
    ('MANAGEMENT', 'Management', 'Management reporting and approvals', true),
    ('AUDITOR', 'Auditor', 'Read-only audit and reporting access', true),
    ('ANALYTICS_ADMIN', 'Analytics Admin', 'All Analytics module permissions', true),
    ('APPROVALS_ADMIN', 'Approvals Admin', 'All Approvals module permissions', true),
    ('AUDIT_ADMIN', 'Audit Admin', 'All Audit module permissions', true),
    ('AUTH_ADMIN', 'Auth Admin', 'All Auth module permissions', true),
    ('COMPANY_MODULE_ADMIN', 'Company Module Admin', 'All Company module permissions', true),
    ('COTTON_ADMIN', 'Cotton Admin', 'All Cotton module permissions', true),
    ('DISPATCH_ADMIN', 'Dispatch Admin', 'All Dispatch module permissions', true),
    ('EMPLOYEES_ADMIN', 'Employees Admin', 'All Employees module permissions', true),
    ('FINANCE_ADMIN', 'Finance Admin', 'All Finance module permissions', true),
    ('FUEL_ADMIN', 'Fuel Admin', 'All Fuel module permissions', true),
    ('MAINTENANCE_ADMIN', 'Maintenance Admin', 'All Maintenance module permissions', true),
    ('PROCUREMENT_ADMIN', 'Procurement Admin', 'All Procurement module permissions', true),
    ('PRODUCTION_ADMIN', 'Production Admin', 'All Production module permissions', true),
    ('QC_ADMIN', 'QC Admin', 'All QC module permissions', true),
    ('REPORTS_ADMIN', 'Reports Admin', 'All Reports module permissions', true),
    ('ROLES_ADMIN', 'Roles Admin', 'All Roles module permissions', true),
    ('SALES_ADMIN', 'Sales Admin', 'All Sales module permissions', true),
    ('SETTINGS_ADMIN', 'Settings Admin', 'All Settings module permissions', true),
    ('TRA_STAMPS_ADMIN', 'Tra Stamps Admin', 'All Tra Stamps module permissions', true),
    ('TRANSPORT_ADMIN', 'Transport Admin', 'All Transport module permissions', true),
    ('USERS_ADMIN', 'Users Admin', 'All Users module permissions', true),
    ('WAREHOUSE_ADMIN', 'Warehouse Admin', 'All Warehouse module permissions', true)
)
INSERT INTO roles (id, code, name, description, "isSystemRole", "isActive", "createdAt", "updatedAt", "createdById")
SELECT 'role-' || lower(replace(code, '_', '-')), code, name, description, is_system_role, true, now(), now(), 'system'
FROM role_seed
ON CONFLICT (code) DO UPDATE
SET name = EXCLUDED.name,
    description = EXCLUDED.description,
    "isSystemRole" = EXCLUDED."isSystemRole",
    "isActive" = true,
    "updatedAt" = now();

-- 2. Permissions
WITH permission_seed(module, resource, action, description) AS (
  VALUES
    ('analytics', 'dashboard', 'read', 'View analytics dashboard'),
    ('analytics', 'financial', 'read', 'View financial analytics'),
    ('analytics', 'operations', 'read', 'View operational analytics'),
    ('approvals', 'request', 'approve', 'Approve/reject approval requests'),
    ('approvals', 'request', 'cancel', 'Cancel approval requests'),
    ('approvals', 'request', 'read', 'View approval requests'),
    ('approvals', 'request', 'reject', 'Reject Approvals Request'),
    ('approvals', 'workflow', 'create', 'Create Approvals Workflow'),
    ('approvals', 'workflow', 'manage', 'Manage approval workflows'),
    ('approvals', 'workflow', 'read', 'View Approvals Workflow'),
    ('approvals', 'workflow', 'update', 'Update Approvals Workflow'),
    ('audit', 'log', 'read', 'View audit logs'),
    ('auth', 'session', 'create', 'Login to the system'),
    ('company', 'branch', 'create', 'Create branches'),
    ('company', 'branch', 'deactivate', 'Deactivate branches'),
    ('company', 'branch', 'read', 'View branches'),
    ('company', 'branch', 'update', 'Edit branches'),
    ('company', 'company', 'create', 'Create companies'),
    ('company', 'company', 'read', 'View company profile'),
    ('company', 'company', 'update', 'Edit company profile'),
    ('company', 'department', 'create', 'Create departments'),
    ('company', 'department', 'deactivate', 'Deactivate departments'),
    ('company', 'department', 'read', 'View departments'),
    ('company', 'department', 'update', 'Edit departments'),
    ('cotton', 'bale', 'create', 'Create cotton bales'),
    ('cotton', 'bale', 'read', 'View cotton bales'),
    ('cotton', 'bale', 'update', 'Update cotton bales'),
    ('cotton', 'buyer', 'create', 'Create cotton buyers'),
    ('cotton', 'buyer', 'read', 'View cotton buyers'),
    ('cotton', 'buyer', 'update', 'Update cotton buyers'),
    ('cotton', 'contract', 'create', 'Create cotton contracts'),
    ('cotton', 'contract', 'read', 'View cotton contracts'),
    ('cotton', 'contract', 'update', 'Update cotton contracts'),
    ('cotton', 'invoice', 'create', 'Create cotton invoices'),
    ('cotton', 'invoice', 'read', 'View cotton invoices'),
    ('cotton', 'invoice', 'update', 'Update cotton invoices'),
    ('cotton', 'lot', 'create', 'Create cotton lots'),
    ('cotton', 'lot', 'read', 'View cotton lots'),
    ('cotton', 'lot', 'update', 'Update cotton lots'),
    ('cotton', 'season', 'create', 'Create cotton seasons'),
    ('cotton', 'season', 'read', 'View cotton seasons'),
    ('cotton', 'season', 'update', 'Update cotton seasons'),
    ('dispatch', 'lot', 'create', 'Receive finished goods inventory lots'),
    ('dispatch', 'lot', 'delete', 'Delete finished goods inventory lots'),
    ('dispatch', 'lot', 'read', 'View finished goods inventory lots'),
    ('dispatch', 'lot', 'update', 'Edit finished goods inventory lots'),
    ('dispatch', 'order', 'create', 'Create dispatch orders'),
    ('dispatch', 'order', 'delete', 'Delete dispatch orders'),
    ('dispatch', 'order', 'deliver', 'Mark dispatch orders delivered'),
    ('dispatch', 'order', 'dispatch', 'Dispatch orders'),
    ('dispatch', 'order', 'read', 'View dispatch orders'),
    ('dispatch', 'order', 'update', 'Edit dispatch orders'),
    ('dispatch', 'product', 'create', 'Create finished goods products'),
    ('dispatch', 'product', 'delete', 'Delete finished goods products'),
    ('dispatch', 'product', 'read', 'View finished goods products'),
    ('dispatch', 'product', 'update', 'Edit finished goods products'),
    ('dispatch', 'report', 'read', 'View dispatch reports'),
    ('employees', 'employee', 'create', 'Create employee records'),
    ('employees', 'employee', 'deactivate', 'Change employee status'),
    ('employees', 'employee', 'read', 'View employee records'),
    ('employees', 'employee', 'update', 'Edit employee records'),
    ('finance', 'account', 'create', 'Create accounts'),
    ('finance', 'account', 'deactivate', 'Deactivate accounts'),
    ('finance', 'account', 'delete', 'Delete Finance Account'),
    ('finance', 'account', 'read', 'View chart of accounts'),
    ('finance', 'account', 'update', 'Edit accounts'),
    ('finance', 'bank', 'create', 'Create bank accounts'),
    ('finance', 'bank', 'deactivate', 'Deactivate bank accounts'),
    ('finance', 'bank', 'delete', 'Delete Finance Bank'),
    ('finance', 'bank', 'read', 'View bank accounts'),
    ('finance', 'bank', 'update', 'Edit bank accounts'),
    ('finance', 'journal', 'create', 'Create journal entries'),
    ('finance', 'journal', 'delete', 'Delete Finance Journal'),
    ('finance', 'journal', 'post', 'Post journal entries'),
    ('finance', 'journal', 'read', 'View journal entries'),
    ('finance', 'journal', 'reverse', 'Reverse journal entries'),
    ('finance', 'journal', 'update', 'Edit journal entries'),
    ('finance', 'payment', 'cancel', 'Cancel payments'),
    ('finance', 'payment', 'complete', 'Complete payments'),
    ('finance', 'payment', 'create', 'Create payments'),
    ('finance', 'payment', 'delete', 'Delete Finance Payment'),
    ('finance', 'payment', 'read', 'View payments'),
    ('finance', 'payment', 'update', 'Edit payments'),
    ('finance', 'report', 'read', 'View financial reports'),
    ('finance', 'tally', 'manage', 'Manage Tally API keys and configuration'),
    ('finance', 'tally', 'read', 'View Tally sync data (vouchers, ledgers, logs)'),
    ('fuel', 'issue', 'create', 'Issue fuel to vehicles'),
    ('fuel', 'issue', 'delete', 'Delete Fuel Issue'),
    ('fuel', 'issue', 'read', 'View fuel issues'),
    ('fuel', 'price', 'create', 'Record fuel prices'),
    ('fuel', 'price', 'read', 'View fuel prices'),
    ('fuel', 'receipt', 'confirm', 'Confirm fuel receipts into tank'),
    ('fuel', 'receipt', 'create', 'Create fuel receipts'),
    ('fuel', 'receipt', 'delete', 'Delete Fuel Receipt'),
    ('fuel', 'receipt', 'read', 'View fuel receipts'),
    ('fuel', 'report', 'read', 'View fuel consumption reports'),
    ('fuel', 'tank', 'create', 'Create fuel tanks'),
    ('fuel', 'tank', 'delete', 'Delete Fuel Tank'),
    ('fuel', 'tank', 'read', 'View fuel tanks'),
    ('fuel', 'tank', 'update', 'Edit fuel tanks'),
    ('maintenance', 'part', 'create', 'Create spare parts'),
    ('maintenance', 'part', 'read', 'View spare parts'),
    ('maintenance', 'part', 'update', 'Edit spare parts'),
    ('maintenance', 'receipt', 'create', 'Receive spare parts into stock'),
    ('maintenance', 'receipt', 'read', 'View spare part receipts'),
    ('maintenance', 'report', 'read', 'View maintenance reports'),
    ('maintenance', 'schedule', 'create', 'Create maintenance schedules'),
    ('maintenance', 'schedule', 'delete', 'Delete Maintenance Schedule'),
    ('maintenance', 'schedule', 'read', 'View maintenance schedules'),
    ('maintenance', 'schedule', 'update', 'Edit maintenance schedules'),
    ('maintenance', 'spare_part', 'create', 'Create Maintenance Spare Part'),
    ('maintenance', 'spare_part', 'delete', 'Delete Maintenance Spare Part'),
    ('maintenance', 'spare_part', 'read', 'View Maintenance Spare Part'),
    ('maintenance', 'spare_part', 'update', 'Update Maintenance Spare Part'),
    ('maintenance', 'workorder', 'complete', 'Complete work orders'),
    ('maintenance', 'workorder', 'create', 'Create work orders'),
    ('maintenance', 'workorder', 'delete', 'Delete Maintenance Workorder'),
    ('maintenance', 'workorder', 'read', 'View work orders'),
    ('maintenance', 'workorder', 'update', 'Edit work orders'),
    ('procurement', 'order', 'create', 'Create purchase orders'),
    ('procurement', 'order', 'delete', 'Delete Procurement Order'),
    ('procurement', 'order', 'read', 'View purchase orders'),
    ('procurement', 'order', 'receive', 'Receive purchase orders'),
    ('procurement', 'order', 'send', 'Send purchase orders'),
    ('procurement', 'order', 'update', 'Edit purchase orders'),
    ('procurement', 'report', 'read', 'View procurement reports'),
    ('procurement', 'request', 'approve', 'Approve purchase requests'),
    ('procurement', 'request', 'create', 'Create purchase requests'),
    ('procurement', 'request', 'delete', 'Delete Procurement Request'),
    ('procurement', 'request', 'read', 'View purchase requests'),
    ('procurement', 'request', 'submit', 'Submit purchase requests'),
    ('procurement', 'request', 'update', 'Edit purchase requests'),
    ('procurement', 'supplier', 'create', 'Create suppliers'),
    ('procurement', 'supplier', 'delete', 'Delete Procurement Supplier'),
    ('procurement', 'supplier', 'read', 'View suppliers'),
    ('procurement', 'supplier', 'update', 'Edit suppliers'),
    ('production', 'batch', 'complete', 'Complete production batches'),
    ('production', 'batch', 'create', 'Create production batches'),
    ('production', 'batch', 'delete', 'Delete Production Batch'),
    ('production', 'batch', 'read', 'View production batches'),
    ('production', 'batch', 'start', 'Start production batches'),
    ('production', 'batch', 'update', 'Edit production batches'),
    ('production', 'line', 'create', 'Create production lines'),
    ('production', 'line', 'delete', 'Delete Production Line'),
    ('production', 'line', 'read', 'View production lines'),
    ('production', 'line', 'update', 'Edit production lines'),
    ('production', 'recipe', 'create', 'Create production recipes'),
    ('production', 'recipe', 'delete', 'Delete Production Recipe'),
    ('production', 'recipe', 'read', 'View production recipes'),
    ('production', 'recipe', 'update', 'Edit production recipes'),
    ('production', 'report', 'read', 'View production reports'),
    ('qc', 'ncr', 'create', 'Create QC NCR'),
    ('qc', 'ncr', 'delete', 'Delete QC NCR'),
    ('qc', 'ncr', 'read', 'View QC NCR'),
    ('qc', 'ncr', 'resolve', 'Resolve QC NCR'),
    ('qc', 'ncr', 'update', 'Update QC NCR'),
    ('qc', 'report', 'read', 'View QC Report'),
    ('qc', 'standard', 'create', 'Create QC Standard'),
    ('qc', 'standard', 'delete', 'Delete QC Standard'),
    ('qc', 'standard', 'read', 'View QC Standard'),
    ('qc', 'standard', 'update', 'Update QC Standard'),
    ('qc', 'test', 'complete', 'Complete QC Test'),
    ('qc', 'test', 'create', 'Create QC Test'),
    ('qc', 'test', 'delete', 'Delete QC Test'),
    ('qc', 'test', 'read', 'View QC Test'),
    ('qc', 'test', 'update', 'Update QC Test'),
    ('reports', 'report', 'read', 'View module reports'),
    ('roles', 'permission', 'assign', 'Assign permissions to roles'),
    ('roles', 'role', 'create', 'Create roles'),
    ('roles', 'role', 'deactivate', 'Deactivate roles'),
    ('roles', 'role', 'read', 'View roles'),
    ('roles', 'role', 'update', 'Edit roles'),
    ('sales', 'customer', 'create', 'Create customers'),
    ('sales', 'customer', 'read', 'View customers'),
    ('sales', 'customer', 'update', 'Edit customers'),
    ('sales', 'kpi', 'manage', 'Manage sales KPI targets'),
    ('sales', 'kpi', 'read', 'View sales KPIs'),
    ('sales', 'order', 'create', 'Create sales orders'),
    ('sales', 'order', 'read', 'View sales orders'),
    ('sales', 'order', 'update', 'Update sales orders'),
    ('sales', 'webhook', 'manage', 'Manage sales webhook settings'),
    ('settings', 'settings', 'read', 'View system settings'),
    ('settings', 'settings', 'update', 'Update system settings'),
    ('tra-stamps', 'stamp', 'activate', 'Activate TRA stamps'),
    ('tra-stamps', 'stamp', 'create', 'Receive TRA stamp batches'),
    ('tra-stamps', 'stamp', 'read', 'View TRA stamps'),
    ('transport', 'assignment', 'create', 'Assign vehicles to drivers'),
    ('transport', 'assignment', 'read', 'View vehicle assignments'),
    ('transport', 'assignment', 'update', 'Update vehicle assignments'),
    ('transport', 'daily-movement', 'create', 'Create daily truck movement reports'),
    ('transport', 'daily-movement', 'read', 'View daily truck movement reports'),
    ('transport', 'daily-movement', 'update', 'Edit and submit daily truck movement reports'),
    ('transport', 'driver', 'create', 'Create driver profiles'),
    ('transport', 'driver', 'delete', 'Delete Transport Driver'),
    ('transport', 'driver', 'read', 'View drivers'),
    ('transport', 'driver', 'update', 'Edit driver profiles'),
    ('transport', 'incident', 'create', 'Report vehicle incidents'),
    ('transport', 'incident', 'delete', 'Delete Transport Incident'),
    ('transport', 'incident', 'read', 'View vehicle incidents'),
    ('transport', 'incident', 'update', 'Update incident records'),
    ('transport', 'trip', 'complete', 'Mark trips as completed'),
    ('transport', 'trip', 'create', 'Create trip orders'),
    ('transport', 'trip', 'delete', 'Delete trip orders'),
    ('transport', 'trip', 'dispatch', 'Dispatch trips'),
    ('transport', 'trip', 'read', 'View trip orders'),
    ('transport', 'trip', 'update', 'Edit trip orders'),
    ('transport', 'vehicle', 'create', 'Create vehicles'),
    ('transport', 'vehicle', 'delete', 'Delete Transport Vehicle'),
    ('transport', 'vehicle', 'read', 'View vehicles'),
    ('transport', 'vehicle', 'update', 'Edit vehicles'),
    ('users', 'user', 'assign_role', 'Assign/remove roles from users'),
    ('users', 'user', 'create', 'Create user accounts'),
    ('users', 'user', 'deactivate', 'Deactivate user accounts'),
    ('users', 'user', 'read', 'View user accounts'),
    ('users', 'user', 'reset_password', 'Reset user passwords'),
    ('users', 'user', 'update', 'Edit user accounts'),
    ('warehouse', 'adjustment', 'approve', 'Approve and apply stock adjustments'),
    ('warehouse', 'adjustment', 'create', 'Create stock adjustments'),
    ('warehouse', 'adjustment', 'read', 'View stock adjustments'),
    ('warehouse', 'adjustment', 'submit', 'Submit adjustments for approval'),
    ('warehouse', 'category', 'create', 'Create item categories'),
    ('warehouse', 'category', 'read', 'View item categories'),
    ('warehouse', 'category', 'update', 'Edit item categories'),
    ('warehouse', 'grn', 'confirm', 'Confirm goods receipt into stock'),
    ('warehouse', 'grn', 'create', 'Create goods received notes'),
    ('warehouse', 'grn', 'read', 'View goods received notes'),
    ('warehouse', 'item', 'create', 'Create items'),
    ('warehouse', 'item', 'delete', 'Delete Warehouse Item'),
    ('warehouse', 'item', 'read', 'View items'),
    ('warehouse', 'item', 'update', 'Edit items'),
    ('warehouse', 'location', 'create', 'Create storage locations'),
    ('warehouse', 'location', 'read', 'View storage locations'),
    ('warehouse', 'location', 'update', 'Edit storage locations'),
    ('warehouse', 'stock', 'read', 'View stock levels'),
    ('warehouse', 'transfer', 'create', 'Create stock transfers'),
    ('warehouse', 'transfer', 'dispatch', 'Dispatch stock transfers'),
    ('warehouse', 'transfer', 'read', 'View stock transfers'),
    ('warehouse', 'transfer', 'receive', 'Receive stock transfers'),
    ('warehouse', 'uom', 'create', 'Create units of measure'),
    ('warehouse', 'uom', 'read', 'View units of measure'),
    ('warehouse', 'uom', 'update', 'Edit units of measure'),
    ('warehouse', 'warehouse', 'create', 'Create warehouses'),
    ('warehouse', 'warehouse', 'delete', 'Delete Warehouse Warehouse'),
    ('warehouse', 'warehouse', 'read', 'View warehouses'),
    ('warehouse', 'warehouse', 'update', 'Edit warehouses')
)
INSERT INTO permissions (id, module, resource, action, description)
SELECT 'perm-' || module || '-' || resource || '-' || action, module, resource, action, description
FROM permission_seed
ON CONFLICT (module, resource, action) DO UPDATE
SET description = EXCLUDED.description;

-- 3. Super Admin and Company Admin receive every permission.
INSERT INTO role_permissions ("roleId", "permissionId", "grantedAt", "grantedById")
SELECT r.id, p.id, now(), 'system'
FROM roles r
CROSS JOIN permissions p
WHERE r.code IN ('SUPER_ADMIN', 'COMPANY_ADMIN')
ON CONFLICT ("roleId", "permissionId") DO NOTHING;

-- 4. Module admin roles receive every permission for their module.
WITH module_role(module, code) AS (
  VALUES
    ('analytics', 'ANALYTICS_ADMIN'),
    ('approvals', 'APPROVALS_ADMIN'),
    ('audit', 'AUDIT_ADMIN'),
    ('auth', 'AUTH_ADMIN'),
    ('company', 'COMPANY_MODULE_ADMIN'),
    ('cotton', 'COTTON_ADMIN'),
    ('dispatch', 'DISPATCH_ADMIN'),
    ('employees', 'EMPLOYEES_ADMIN'),
    ('finance', 'FINANCE_ADMIN'),
    ('fuel', 'FUEL_ADMIN'),
    ('maintenance', 'MAINTENANCE_ADMIN'),
    ('procurement', 'PROCUREMENT_ADMIN'),
    ('production', 'PRODUCTION_ADMIN'),
    ('qc', 'QC_ADMIN'),
    ('reports', 'REPORTS_ADMIN'),
    ('roles', 'ROLES_ADMIN'),
    ('sales', 'SALES_ADMIN'),
    ('settings', 'SETTINGS_ADMIN'),
    ('tra-stamps', 'TRA_STAMPS_ADMIN'),
    ('transport', 'TRANSPORT_ADMIN'),
    ('users', 'USERS_ADMIN'),
    ('warehouse', 'WAREHOUSE_ADMIN')
)
INSERT INTO role_permissions ("roleId", "permissionId", "grantedAt", "grantedById")
SELECT r.id, p.id, now(), 'system'
FROM module_role mr
JOIN roles r ON r.code = mr.code
JOIN permissions p ON p.module = mr.module
ON CONFLICT ("roleId", "permissionId") DO NOTHING;

-- 5. Read-focused baseline roles. These are additive and do not remove custom grants.
INSERT INTO role_permissions ("roleId", "permissionId", "grantedAt", "grantedById")
SELECT r.id, p.id, now(), 'system'
FROM roles r
JOIN permissions p ON p.action = 'read'
WHERE r.code IN ('MANAGEMENT', 'AUDITOR')
ON CONFLICT ("roleId", "permissionId") DO NOTHING;

-- 6. Ensure the admin user is attached to SUPER_ADMIN when present.
INSERT INTO user_roles (id, "userId", "roleId", "assignedAt", "assignedById")
SELECT 'ur-admin-super-admin', u.id, r.id, now(), 'system'
FROM users u
JOIN roles r ON r.code = 'SUPER_ADMIN'
WHERE lower(u.username) = 'admin'
ON CONFLICT DO NOTHING;

COMMIT;

-- Summary: 245 permissions, 28 roles, 22 module admin roles.
